apiVersion: v1
kind: Pod
metadata:
  name: handle-signal-prestop
spec:
  shareProcessNamespace: true
  containers:
  - name: handle-signal-prestop
    image: torumakabe/handle-signal:0.0.2
    lifecycle:
      preStop:
        exec:
          command: ["sh", "-c", "sleep 1; echo killing > /dev/termination-log; sleep 2"]
