apiVersion: v1
kind: Service
metadata:
  name: squid
  labels:
    app: squid
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 10.240.0.200
  ports:
    - port: 3128
      targetPort: 3128
      protocol: TCP
  selector:
    app: squid
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  labels:
    app: squid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
        - name: squid
          image: sameersbn/squid:3.5.27-1
          ports:
            - containerPort: 3128
              protocol: TCP
          volumeMounts:
            - mountPath: /var/spool/squid
              name: data
      volumes:
        - name: data
          emptyDir: {}