apiVersion: v1
kind: Pod
metadata:
  name: eval-pod-identity
  labels:
    app: eval-pod-identity
    aadpodidbinding: sample
spec:
  containers:
  - name: curl
    image: appropriate/curl
    args:
    - /bin/sh
    - -c
    - >
      while true;
      do
        sleep 1;
      done